# Agent OS Mobile Configuration
# React Native + Expo Edition

# Refer to the Agent OS Mobile documentation in this repository
# Original Agent OS: https://buildermethods.com/agent-os

agent_os_version: Mobile-1.0.0
agent_os_base_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: false

project_types:
  default:
    instructions: ~/.agent-os/instructions
    standards: ~/.agent-os/standards

  # type_a:
  #   instructions: ~/.agent-os/project_types/type_a/instructions
  #   standards: ~/.agent-os/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.agent-os/project_types/type_b/instructions
  #   standards: ~/.agent-os/project_types/type_b/standards

default_project_type: default
